#define SPI_SCK_PIN GP2
#define SPI_MOSI_PIN GP3
#define SPI_MISO_PIN GP0
#define PMW33XX_CS_PIN GP1
#define SPI_DRIVER SPID0
#define PMW33XX_LIFTOFF_DISTANCE 0x03
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X


#define JOYSTICK_BUTTON_COUNT 0
#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_RESOLUTION 12

#define I2C_DRIVER I2CD1
#define I2C0_SDA_PIN GP4
#define I2C0_SCL_PIN GP3

#define ENCODER_A_PINS { GP21, GP26 }
#define ENCODER_B_PINS { GP20, GP22 }
#define ENCODER_DIRECTION_FLIP