BOOTLOADER = rp2040


POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360


# Joystick region
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog

# OLED region
OLED_ENABLED = yes
OLED_DRIVER_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

# Encoder region
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes